##############################
# Guayamas mapping and profiling queues
##############################

executable = /home/GLBRCORG/emcdaniel/MicDiv/executables/guayamas_mapping_profiling.sh

request_cpus = 10
request_memory = 150GB
arguments = $(reads)

output = /home/GLBRCORG/emcdaniel/MicDiv/outs/$(Cluster)_$(Process)_guay_mapping.out
error = /home/GLBRCORG/emcdaniel/MicDiv/errs/$(Cluster)_$(Process)_guay_mapping.err
log = /home/GLBRCORG/emcdaniel/MicDiv/logs/$(Cluster)_$(Process)_guay_mapping.log

queue reads from queues/guayamas_metagenomes.txt