##############################
# permafrost mapping and profiling queues
##############################

executable = /home/GLBRCORG/emcdaniel/MicDiv/executables/permafrost_mapping_profiling.sh

request_cpus = 6
request_memory = 40GB
arguments = $(reads)

output = /home/GLBRCORG/emcdaniel/MicDiv/outs/$(Cluster)_$(Process)_permafrost_mapping.out
error = /home/GLBRCORG/emcdaniel/MicDiv/errs/$(Cluster)_$(Process)_permafrost_mapping.err
log = /home/GLBRCORG/emcdaniel/MicDiv/logs/$(Cluster)_$(Process)_permafrost_mapping.log

queue reads from queues/permafrost_metagenomes.txt