##############################
# inStrain profiles
##############################

executable = /home/GLBRCORG/emcdaniel/MicDiv/executables/POB-inStrain-profile-queue.sh

request_cpus = 6
request_memory = 150GB
arguments = $(genome) $(mapping)

output = /home/GLBRCORG/emcdaniel/MicDiv/outs/$(Cluster)_$(Process)_profile.out
error = /home/GLBRCORG/emcdaniel/MicDiv/errs/$(Cluster)_$(Process)_profile.err
log = /home/GLBRCORG/emcdaniel/MicDiv/logs/$(Cluster)_$(Process)_profile.log

queue genome,mapping from queues/POB-inStrain-profile-queues.txt