#! /bin/bash 

for file in *_1.fastq_qced_ref_R1.fastq; do
	name=$(basename $file _1.fastq_qced_ref_R1.fastq);
	sed 's/ 1:N:0//' $file > ${name}_1.fastq.qced.ref.modf.fastq;
done

for file in *_2.fastq_qced_ref_R2.fastq; do
	name=$(basename $file _2.fastq_qced_ref_R2.fastq);
	sed 's/ 2:N:0//' $file > ${name}_2.fastq.qced.ref.modf.fastq;
done
	